package ru.joxaren;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class GeneratedKeysStatement {

    public static void main(String[] args) {

        //Получение атогенерируемого id при insert

        String sql = "INSERT INTO info (data) values ('autogenerated')";

        try(Connection connection = ConnectionManager.open()){
            Statement statement = connection.createStatement();
            int result = statement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
            ResultSet resultSet = statement.getGeneratedKeys();

            if(resultSet.next())
                System.out.println(resultSet.getInt(1));

        }catch (SQLException e){
            throw new RuntimeException(e);
        }

    }
}
