package ru.joxaren;

import java.sql.*;

public class Main {
    public static void main(String[] args){

        /*
        String sql = "CREATE TABLE IF NOT EXISTS info" +
                "(id SERIAL PRIMARY KEY," +
                "data TEXT NOT NULL);";

        String sql = "insert into info (data) values" +
                " ('test1')," +
                " ('test2')," +
                " ('test3')," +
                " ('test4');"+
        " insert into info (data) values" +
                " ('test1')," +
                " ('test2')," +
                " ('test3')," +
                " ('test4');";


        String sql = "SELECT * FROM ticket";

         */


        String sql = "INSERT INTO info (data) values ('autogenerated');";

        try (Connection connection = ConnectionManager.get();
            Statement statement = connection.createStatement()){
             /*
            int executeUpdate = statement.executeUpdate(sql);
            System.out.println(executeUpdate);
            System.out.println(statement.getUpdateCount());
            //System.out.println(connection.getTransactionIsolation());


            ResultSet resultSet = statement.executeQuery(sql);

            while (resultSet.next()){
                System.out.print(resultSet.getInt("id") + " ");
                System.out.print(resultSet.getDouble("cost") + " ");
                System.out.print(resultSet.getString("passenger_name") + "\n");
            }*/

            int executeUpdate = statement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
            if(statement.getGeneratedKeys().next())
            System.out.println(statement.getGeneratedKeys().getInt("id"));

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }
}